const products = [
  {
    _id: '1',
    partName: "Oil Filter",
    partNumber: "OF12345",
    partDescription: "Standard oil filter for engines.",
    inStock: 20,
    onOrder: 5,
    warranty: "1 year",
    reorderThreshold: 5,
    autoReorder: true,
    carInfo: {
      make: "Toyota",
      model: "Camry",
      year: 2021,
    },
  },
  {
    _id: '2',
    partName: "Brake Pad",
    partNumber: "BP67890",
    partDescription: "Ceramic brake pads for enhanced stopping.",
    inStock: 50,
    onOrder: 10,
    warranty: "2 years",
    reorderThreshold: 10,
    autoReorder: true,
    carInfo: {
      make: "Ford",
      model: "Mustang",
      year: 2020,
    },
  },
  {
    _id: '3',
    partName: "Air Filter",
    partNumber: "AF11223",
    partDescription: "Air filter for improved engine performance.",
    inStock: 30,
    onOrder: 0,
    warranty: "1 year",
    reorderThreshold: 10,
    autoReorder: false,
    carInfo: {
      make: "Honda",
      model: "Civic",
      year: 2022,
    },
  },
  {
    _id: '4',
    partName: "Spark Plug",
    partNumber: "SP44556",
    partDescription: "Spark plug for optimal engine ignition.",
    inStock: 100,
    onOrder: 20,
    warranty: "3 years",
    reorderThreshold: 30,
    autoReorder: true,
    carInfo: {
      make: "Chevrolet",
      model: "Impala",
      year: 2019,
    },
  },
  {
    _id: '5',
    partName: "Windshield Wiper",
    partNumber: "WW78901",
    partDescription: "Durable windshield wipers for clear vision.",
    inStock: 40,
    onOrder: 5,
    warranty: "6 months",
    reorderThreshold: 15,
    autoReorder: false,
    carInfo: {
      make: "Tesla",
      model: "Model 3",
      year: 2021,
    },
  },
];
